
CREATE DATABASE "TODO-DB"
	WITH
	OWNER = POSTGRES
	ENCODING = 'UTF8'
	TABLESPACE = pg_default
	CONNECTION LIMIT = -1;
	
	
--DROP ROLE IF EXISTS admin;

CREATE ROLE todo LOGIN PASSWORD 'todotodo';
GRANT ALL PRIVILEGES ON DATABASE "TODO-DB" to todo;

create schema todoschema AUTHORIZATION todo;


create table todoschema.test_users(
	user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	name varchar(100)
)

create table todoschema.greetings(
	greeting_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	message varchar(250),
	user_id integer,
	constraint foreign key greeting_fkey1 user_id references test_users(user_id) on update no action on delete cascade
)